Change Dropdown designs
PVP-K409/fit-flow pull request #41
Opened 2024-04-06 12:08 UTC by ugnspa

Designed dropdown menu for Goal creation
![433563379_826952955918080_1849612743223887501_n](https://github.com/PVP-K409/fit-flow/assets/125737106/319a98e3-ce4c-45de-aa13-f8ccda6db0a5)
![434612690_7798886140162419_4821891110495448797_n](https://github.com/PVP-K409/fit-flow/assets/125737106/87c6d573-6e20-4d72-ba5f-e5b3490283a5)

2024-04-07 17:49 UTC, mantasjasikenas requested changes
Looks good but please move texts to string resources

2024-04-07 17:49 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/goals/GoalCreation.kt
> +                text = "Create Goal",
Move text to string resources

2024-04-07 17:49 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/goals/GoalCreation.kt
> +                label = "Period",
Move text to string resources

2024-04-07 17:49 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/goals/GoalCreation.kt
> +                        label = "Exercise",
Move text to string resources

2024-04-07 17:49 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/goals/GoalCreation.kt
> +                        label = "Distance",
Move text to string resources

2024-04-07 17:49 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/goals/GoalCreation.kt
> +                text = selectedOption.ifEmpty { "Select an option" },
Move text to string resources

2024-04-08 07:03 UTC, mantasjasikenas approved these changes

2024-04-08 07:34 UTC, paulius-mongirdas approved these changes

2024-04-08 07:37 UTC, merged