Sga 105 add preset locations for decorations in aquarium
PVP-K409/fit-flow pull request #62
Opened 2024-04-25 19:50 UTC by paulius-mongirdas

- Added box boundary inside aquarium that limits decoration placement (around sand)
- Decoration positions are saved to database
- Initial position for placed decoration is randomized (in practice it is difficult to completely remove overlapping, so a random initial position works fairly well).

2024-04-25 20:16 UTC, mantasjasikenas requested changes

2024-04-25 20:16 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/aquarium/component/Aquarium.kt
> +            // CoralCuspPlant()
Remove these comments

2024-04-25 20:16 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/aquarium/component/Aquarium.kt
> +                                    inventoryViewModel = inventoryViewModel,
I would suggest to use callbacks, not full inventoryViewModel. It would make component more testable and not so dependant on inventory viewmodel

2024-04-25 20:33 UTC, mantasjasikenas approved these changes

2024-04-26 00:08 UTC, ugnspa commented
Expand top boundary, because now anchor can only be dragged left and right

2024-04-26 07:46 UTC, paulius-mongirdas commented
> Expand top boundary, because now anchor can only be dragged left and right

There is a problem that if i expand top boundary, then smaller height decorations (like Cardio Crab) can exit sand area and float in water. This issue might be resolved if all decorations had same dimensions, but I am not yet sure what is the best way to assure that.

2024-04-26 15:08 UTC, ugnspa approved these changes

2024-04-26 15:09 UTC, merged