SGA-128-Friend-invites
PVP-K409/fit-flow pull request #82
Opened 2024-05-15 11:20 UTC by GillWell

## Summary of the Pull Request

SGA 128
Create a friend invite screen to show received friend requests, functions for accepting, declining, sending friend requests.

SGA 129
Create a screen to show current friends, functions to get the friends data and remove them

## PR Checklist

SGA 128
- [ ] “Friends” screen is accessed from avatar click dropdown
- [ ] Friend invite functions should be displayed inside a tab “Friend invites” within “Friends” screen
- [ ] Friend invites tab should also display received invites list
- [ ] Received invites can be accepted or denied

SGA 129
- [ ] Friends list should be displayed inside a tab “Friends list” within “Friends” screen

## Detailed Description of the Pull Request / Additional comments
To send a friend request the user needs to use the search bar to first find the user then send a friend request. User who have sent a friend request will be showed below, the user can accept or decline. Can't send friend request to yourself, friends, users that have sent a friend request already. Friend list shows users that you are friends with. Able to remove friends

2024-05-15 15:32 UTC, mantasjasikenas requested changes

2024-05-15 15:32 UTC, mantasjasikenas commented on app/src/main/res/values/strings.xml
> +    <string name="Searched_user">User found by searching for their email address</string>
Should start with lowercase

2024-05-15 15:32 UTC, mantasjasikenas commented on app/src/main/res/values/strings.xml
> +    <string name="Searched_users">Searched user</string>
Should start with lowercase

2024-05-15 15:32 UTC, mantasjasikenas commented on app/src/main/res/values/strings.xml
> +    <string name="Already_friends">You are already friends with this user</string>
Should start with lowercase

2024-05-15 15:32 UTC, mantasjasikenas commented on app/src/main/res/values/strings.xml
> +    <string name="Self_friend">Can\'t send a friend request to yourself!</string>
Should start with lowercase

2024-05-15 15:32 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/friends/FriendRequestScreen.kt
> +                label = { Text("Send a friend request to") },
Move text to string resources

2024-05-15 15:32 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/friends/FriendsScreen.kt
> +            verticalArrangement = Arrangement.Center,
Arrange elements in top of container (verticalArrangement = Arrangement.Top)

2024-05-15 15:32 UTC, mantasjasikenas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/friends/FriendRequestScreen.kt
> +fun FriendRequestContent(
Arrange elements in top of container

2024-05-15 16:12 UTC, mantasjasikenas approved these changes

2024-05-15 16:35 UTC, mantasjasikenas commented
Please add missing strings in the Lithuanian language

2024-05-15 20:32 UTC, paulius-mongirdas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/friends/FriendCard.kt
> +                    },
Maybe add confirmation dialog (like in market purchases) if user really wants to remove friend.

2024-05-15 20:32 UTC, paulius-mongirdas commented on app/src/main/java/com/github/k409/fitflow/ui/screen/friends/FriendsListScreen.kt
Friends list is not refreshed when friend request is accepted. This seems to be an issue related to device API level, as it works fine on API 34, but does not on 29.

2024-05-16 10:42 UTC, paulius-mongirdas commented on app/src/main/res/values-lt/strings.xml
> +    <string name="sure_to_remove_friend">Ar jūs tikrai norite pašilinti draugą </string>
Spelling

2024-05-16 10:48 UTC, paulius-mongirdas approved these changes

2024-05-16 10:48 UTC, merged